In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('pharmacologically_active.csv')
df = df[df['PDB ID'].notna()]
len(df)

846

In [23]:
df

,ID,Name,Gene Name,GenBank Protein ID,GenBank Gene ID,UniProt ID,Uniprot Title,PDB ID,GeneCard ID,GenAtlas ID,HGNC ID,Species,Drug IDs
1,4,Coagulation factor XIII A chain,F13A1,182309.0,M22001,P00488,F13A_HUMAN,1EVU; 1EX0; 1F13; 1FIE; 1GGT; 1GGU; 1GGY; 1QRK...,NaN,F13A1,HGNC:3531,Humans,DB11300; DB11311; DB11571; DB13151
2,5,"Nitric oxide synthase, inducible",NOS2,292242.0,L09210,P35228,NOS2_HUMAN,1NSI; 2LL6; 2NSI; 3E7G; 3EJ8; 3HR4; 4CX7; 4NOS,NaN,NOS2A,HGNC:7873,Humans,DB05383; DB08814
3,8,"NAD(P) transhydrogenase, mitochondrial",NNT,1110520.0,U40490,Q13423,NNTM_HUMAN,1DJL; 1PT9; 1U31,NaN,NNT,HGNC:7863,Humans,DB09092
7,14,Tyrosine-protein kinase ABL1,ABL1,28237.0,X16416,P00519,ABL1_HUMAN,1AB2; 1ABL; 1AWO; 1BBZ; 1JU5; 1OPL; 1ZZP; 2ABL...,NaN,ABL1,HGNC:76,Humans,DB00619; DB01254; DB04868; DB06616; DB08896; D...
8,15,High affinity immunoglobulin epsilon receptor ...,FCER1A,31318.0,X06948,P12319,FCERA_HUMAN,1ALS; 1ALT; 1F2Q; 1F6A; 1J86; 1J87; 1J88; 1J89...,NaN,FCER1A,HGNC:3609,Humans,DB00043; DB00895
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,3457,T-cell surface glycoprotein CD3 gamma chain,CD3G,NaN,BC113830,P09693,CD3G_HUMAN,1SY6,NaN,CD3G,HGNC:1675,Humans,DB16678
1457,3458,T-cell surface glycoprotein CD3 zeta chain,CD247,NaN,BC025703,P20963,CD3Z_HUMAN,1TCE; 1YGR; 2HAC; 2OQ1; 3IK5; 3IOZ; 4XZ1,NaN,CD247,HGNC:1677,Humans,DB16678
1459,12575,RAC-gamma serine/threonine-protein kinase,AKT3,NaN,NaN,Q9Y243,AKT3_HUMAN,2X18,NaN,NaN,HGNC:393,Humans,DB12218
1460,12705,Tumor necrosis factor receptor superfamily mem...,NGFR,NaN,NaN,P08138,TNR16_HUMAN,2N80; 2N83; 2N97; 3EWV; 5ZGG; 7CSQ,NaN,NaN,HGNC:7809,Humans,DB13926
1461,14802,Presenilin-1,PSEN1,NaN,NaN,P49768,PSN1_HUMAN,2KR6; 4UIS; 5A63; 5FN2; 5FN3; 5FN4; 5FN5; 6IDF...,NaN,NaN,HGNC:9508,Humans,DB12005

In [24]:
lst_protein = [protein.split(';')[0] for protein in df['PDB ID']]

In [25]:
dti_dataset = {'PDB ID': lst_protein, 'Drug IDs': df['Drug IDs']}
dti_dataset = pd.DataFrame(dti_dataset)

# Display the DataFrame
dti_dataset.to_csv('dti_dataset.csv')

In [26]:
dti_dataset

     PDB ID                                           Drug IDs
1      1EVU                 DB11300; DB11311; DB11571; DB13151
2      1NSI                                   DB05383; DB08814
3      1DJL                                            DB09092
7      1AB2  DB00619; DB01254; DB04868; DB06616; DB08896; D...
8      1ALS                                   DB00043; DB00895
...     ...                                                ...
1456   1SY6                                            DB16678
1457   1TCE                                            DB16678
1459   2X18                                            DB12218
1460   2N80                                            DB13926
1461   2KR6                                            DB12005

[846 rows x 2 columns]